# Generated by Django 3.0.7 on 2020-06-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proizvodi', '0002_remove_proizvodi_kratakopis'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetaljiPretrage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=120)),
                ('proizvod', models.ManyToManyField(blank=True, to='proizvodi.Proizvodi')),
            ],
        ),
    ]
