# Generated by Django 3.0.7 on 2020-07-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepti', '0004_auto_20200703_0614'),
        ('detalji_za_pretragu', '0002_auto_20200619_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceptiPretraga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trazi', models.CharField(max_length=120)),
                ('recept', models.ManyToManyField(blank=True, to='recepti.Recept')),
            ],
        ),
    ]
