# Generated by Django 3.0.7 on 2020-07-10 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detalji_za_pretragu', '0003_receptipretraga'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detaljipretrage',
            options={'verbose_name_plural': 'Proizvodi Pretraga tags'},
        ),
        migrations.AlterModelOptions(
            name='receptipretraga',
            options={'verbose_name_plural': 'Recepti Pretraga tags'},
        ),
    ]
