# Generated by Django 3.0.7 on 2020-06-22 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placanja', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placanje',
            options={'verbose_name_plural': 'Placanja'},
        ),
    ]
