# Generated by Django 3.0.7 on 2020-06-22 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placanja', '0002_auto_20200622_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placanje',
            old_name='korisnik',
            new_name='user',
        ),
    ]
