# Generated by Django 3.0.7 on 2020-06-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placanja', '0004_placanje_postarina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placanje',
            name='postarina',
            field=models.PositiveIntegerField(default=250),
        ),
    ]
