# Generated by Django 3.0.7 on 2020-06-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placanja', '0005_auto_20200624_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='placanje',
            name='ukupno_sa_postarinom',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='placanje',
            name='postarina',
            field=models.IntegerField(default=250.0),
        ),
    ]
