# Generated by Django 3.0.7 on 2020-07-11 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proizvodi', '0002_remove_proizvodi_kratakopis'),
        ('placanja', '0008_auto_20200711_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacanjeKolicina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolicina_proizvoda', models.IntegerField(default=1)),
                ('proizvod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proizvodi.Proizvodi')),
            ],
        ),
        migrations.AddField(
            model_name='placanje',
            name='kolicina',
            field=models.ManyToManyField(blank=True, null=True, to='placanja.PlacanjeKolicina'),
        ),
    ]
