# Generated by Django 3.0.7 on 2020-07-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placanja', '0009_auto_20200711_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='placanjekolicina',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
