# Generated by Django 3.0.7 on 2020-07-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placanja', '0010_placanjekolicina_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placanjekolicina',
            options={'verbose_name_plural': 'PlacanjeKolicina'},
        ),
        migrations.AddField(
            model_name='placanjekolicina',
            name='total_ukupno',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
