# Generated by Django 3.0.7 on 2020-07-12 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placanja', '0011_auto_20200712_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placanjekolicina',
            old_name='total_ukupno',
            new_name='totalukupno',
        ),
    ]
