# Generated by Django 3.0.7 on 2020-07-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placanja', '0012_auto_20200712_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='placanjekolicina',
            name='postarina',
            field=models.IntegerField(default=250),
        ),
        migrations.AlterField(
            model_name='placanje',
            name='ukupno',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='placanje',
            name='ukupno_sa_postarinom',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='placanjekolicina',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='placanjekolicina',
            name='totalukupno',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
