# Generated by Django 3.0.7 on 2020-07-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placanja', '0013_auto_20200712_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placanjekolicina',
            name='postarina',
        ),
        migrations.RemoveField(
            model_name='placanjekolicina',
            name='totalukupno',
        ),
        migrations.AddField(
            model_name='placanje',
            name='ukupno_bez_postarine',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
