# Generated by Django 3.0.7 on 2020-07-13 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placanja', '0015_auto_20200713_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placanje',
            name='ukupno',
        ),
    ]
