# Generated by Django 3.0.7 on 2020-07-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placanja', '0016_remove_placanje_ukupno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placanje',
            name='kolicina',
            field=models.ManyToManyField(blank=True, to='placanja.PlacanjeKolicina'),
        ),
    ]
