# Generated by Django 3.0.7 on 2020-06-18 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proizvodi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proizvodi',
            name='kratakOpis',
        ),
    ]
