# Generated by Django 3.0.7 on 2020-06-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porudzbine', '0002_auto_20200627_1148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='porudzbina',
            options={'verbose_name_plural': 'Porudzbina'},
        ),
        migrations.AddField(
            model_name='porudzbina',
            name='postarina_ukupno',
            field=models.DecimalField(decimal_places=1, default=250.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='porudzbina',
            name='ukupno',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=6),
        ),
    ]
