# Generated by Django 3.0.7 on 2020-06-30 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porudzbine', '0003_auto_20200630_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='porudzbina',
            old_name='narudzbina',
            new_name='placanje',
        ),
    ]
