# Generated by Django 3.0.7 on 2020-07-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porudzbine', '0006_auto_20200630_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porudzbina',
            name='postarina_ukupno',
            field=models.DecimalField(decimal_places=2, default=250.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='porudzbina',
            name='ukupno',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
