# Generated by Django 3.0.7 on 2020-07-13 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porudzbine', '0007_auto_20200702_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='porudzbina',
            old_name='ukupno',
            new_name='ukupno_sa_postarinom',
        ),
    ]
