# Generated by Django 3.0.7 on 2020-07-13 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porudzbine', '0009_auto_20200713_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='porudzbina',
            old_name='placanje_narudzbina',
            new_name='broj_placanja',
        ),
        migrations.RemoveField(
            model_name='porudzbina',
            name='postarina_ukupno',
        ),
        migrations.RemoveField(
            model_name='porudzbina',
            name='ukupno_bez_postarine',
        ),
        migrations.RemoveField(
            model_name='porudzbina',
            name='ukupno_sa_postarinom',
        ),
    ]
