# Generated by Django 3.0.7 on 2020-07-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porudzbine', '0011_auto_20200713_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='porudzbina',
            name='postarina_ukupno',
            field=models.DecimalField(decimal_places=2, default=250.0, max_digits=100),
        ),
        migrations.AddField(
            model_name='porudzbina',
            name='ukupno_bez_postarine',
            field=models.DecimalField(decimal_places=2, default=250.0, max_digits=100),
        ),
        migrations.AddField(
            model_name='porudzbina',
            name='ukupno_sa_postarinom',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
