# Generated by Django 3.0.7 on 2020-07-02 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepti', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recepti',
            options={'verbose_name_plural': 'Recepti'},
        ),
        migrations.RenameField(
            model_name='recepti',
            old_name='recepti',
            new_name='recept',
        ),
    ]
