# Generated by Django 3.0.7 on 2020-07-02 18:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recepti', '0002_auto_20200702_1935'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recepti',
            new_name='Post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='recept',
            new_name='post',
        ),
    ]
