# Generated by Django 3.0.7 on 2020-07-03 04:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recepti', '0003_auto_20200702_2041'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Recept',
        ),
    ]
